build:
  maxIssues: 0
  excludeCorrectable: false
  weights:
    # complexity: 2
    # LongParameterList: 1
    # style: 1
    # comments: 1

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false
  # when writing own rules with new properties, include the property path here
  # excludes: 'build/tmp/.*'

# ... (rest of standard detekt config can be added here, or it will use defaults)
